version: '3.9'

services:
  db:
    image: mysql:5.7
    volumes:
      - sandy_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - wp_network
    restart: always
    environment:
      PMA_HO
